server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crop_db?createDatabaseIfNotExist=true
    username: root
    password: 1212
  jpa:
    hibernate:
      ddl-auto: update
